apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: backend_image
          imagePullPolicy: Never
          restartPolicy: Never
          name: backend
          envFrom:
          - secretRef:
              name: backend-secret
          ports:
            - containerPort: 5000
              name: gunicorn
          command:
            - "bash"
            - "-c"
            - "sleep 60m"
            - "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000"
      imagePullSecrets:
        - name: dockerregkey
