apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app.kubernetes.io/name: postgresql