apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DJANGO_LOGLEVEL: "info"
  DEBUG: "False"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DJANGO_SETTINGS_MODULE: "app.settings"
  SECRET_KEY: "'*n*f0zqlu+cgn&m*sd3^qkz9b=nw6db(tfo$156o9ag-%2f_eq'"
  DJANGO_ALLOWED_HOSTS: "165.22.201.149,localhost,127.0.0.1,website.com,m.website.com,web.website.com,api.website.com"
  SQL_ENGINE: "django.db.backends.postgresql_psycopg2"
  SQL_DATABASE: "websitedb"
  SQL_USER: "admin"
  SQL_PASSWORD: "AVNS_tetr6hwN_HtBLymVJ0i"
  SQL_HOST: "postgresserver-postgresql"
  SQL_PORT: "5432"
  SENDGRID_API_PASS: "SG.newly_generated_password.Lt1Plqd1NAfJny4mVfpsJyIe27PMfmCQQZbxfpzNO4w"
  SENDGRID_API_KEY: "newly_generated_key"
  WOKEEPOCH: "1577840400000"
  CELERY_BROKER_URL: "amqp://api:manager@5-180-180-127.cloud-xip.com:5672/api"
  CELERY_RESULT_BACKEND: "redis://default:ve4s0MUu1sUc@5-180-180-224.cloud-xip.com:6379"
  SOCK_REDIS: "redis://default:ve4s0MUu1sUc@5-180-180-224.cloud-xip.com:6379"